/*
 * npu_cnn_driver.h - shared driver loop for running a whole CNN (as a
 * list of NpuAccel calls generated by tools/model_to_npu_calls.py)
 * through the NPU accelerator model and reporting a summary.
 *
 * Used by npu_mobilenetv2_bench.c / npu_yolov8n_bench.c - see those for
 * the ~5 lines needed to point this driver at a specific generated
 * model header.
 */
#ifndef NPU_CNN_DRIVER_H
#define NPU_CNN_DRIVER_H

#include <stdio.h>
#include <string.h>

#include "common/gem5_accel.h"

/* npu_call struct is defined by each generated <model>_calls.h; declaring
 * it here too (identical layout) would violate ODR in a shared header,
 * so this driver is written generically against void* + accessor macros
 * instead - see the NPU_CALL_* macros used below, which the includer
 * must NOT redefine (they just name the struct fields, unchanged). */

static uint8_t g_npu_src_buf[4096] __attribute__((aligned(4096)));
static uint8_t g_npu_dst_buf[4096] __attribute__((aligned(4096)));

/* T must be the generated `struct npu_call` type (identical definition
 * in every <model>_calls.h, so this is safe to use with any of them). */
#define RUN_NPU_CALLS(calls, num_calls, model_name)                       \
    run_npu_calls_impl((const struct npu_call *)(calls), (num_calls),     \
                        (model_name))

static inline void
run_npu_calls_impl(const struct npu_call *calls, int num_calls,
                    const char *model_name)
{
    uint64_t total_cycles = 0;
    uint64_t dense_cycles = 0, depthwise_cycles = 0;
    int dense_count = 0, depthwise_count = 0, failed_count = 0;

    printf("=== %s: running %d NPU calls ===\n", model_name, num_calls);

    for (int i = 0; i < num_calls; i++) {
        const struct npu_call *c = &calls[i];
        uint32_t bytes = c->len_bytes;
        if (bytes == 0 || bytes > sizeof(g_npu_src_buf))
            bytes = sizeof(g_npu_src_buf);
        memset(g_npu_src_buf, 0xA5, bytes);

        long rc = gem5_accel_start(ACCEL_ID_NPU, g_npu_src_buf,
                                    g_npu_dst_buf, bytes, c->param0,
                                    c->param1);
        if (rc != 0) {
            printf("  [%5d] %-36s start FAILED rc=%ld\n", i, c->label, rc);
            failed_count++;
            continue;
        }

        gem5_accel_wait(ACCEL_ID_NPU);
        long cycles = gem5_accel_cycles(ACCEL_ID_NPU);
        total_cycles += (uint64_t)cycles;

        if (c->param1 & 1) {
            depthwise_cycles += (uint64_t)cycles;
            depthwise_count++;
        } else {
            dense_cycles += (uint64_t)cycles;
            dense_count++;
        }

        /* Printing every single call for a 7000+ call model would flood
         * the log; print progress every 200 calls plus the last one. */
        if ((i % 200) == 0 || i == num_calls - 1) {
            printf("  [%5d/%5d] %-36s cycles=%-8ld running_total=%llu\n",
                   i + 1, num_calls, c->label, cycles,
                   (unsigned long long)total_cycles);
        }
    }

    printf("\n--- %s summary ---\n", model_name);
    printf("  total calls         : %d (dense=%d, depthwise=%d, "
           "failed=%d)\n",
           num_calls, dense_count, depthwise_count, failed_count);
    printf("  total device cycles : %llu\n",
           (unsigned long long)total_cycles);
    if (total_cycles > 0) {
        printf("  dense cycles        : %llu (%lu%%)\n",
               (unsigned long long)dense_cycles,
               (unsigned long)(100 * dense_cycles / total_cycles));
        printf("  depthwise cycles    : %llu (%lu%%)\n",
               (unsigned long long)depthwise_cycles,
               (unsigned long)(100 * depthwise_cycles / total_cycles));
    }
}

#endif /* NPU_CNN_DRIVER_H */
